name: P   I   E   F   A   C   E
favicon: null
layout_spectrum: 0.49542
typography_spectrum: 0.4974
title: Reluctant Portraits
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8e8e8e'
    - '#545454'
    - '#000000'
    - '#c5c5c5'
    - '#f4f4f4'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
