name: P   I   E   F   A   C   E
favicon: null
layout_spectrum: 0.24806
typography_spectrum: 0.4974
title: R E L U C T A N T    P O R T R A I T S
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dee5ed'
    - '#996f00'
    - '#c5ae00'
    - '#030200'
    - '#008961'
  brandStrength: 0.0625
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
