name: pieface
favicon: null
layout_spectrum: 1
typography_spectrum: 0.28085
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8e8e8e'
    - '#545454'
    - '#000000'
    - '#c5c5c5'
    - '#f4f4f4'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5651370473206043
  rhythmicContrast: 0
purpose: []
