name: P   I   E   F   A   C   E
favicon: null
layout_spectrum: 0.60227
typography_spectrum: 0.25888
title: Reluctant Portraits
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8e8e8e'
    - '#545454'
    - '#000000'
    - '#c5c5c5'
    - '#f4f4f4'
  brandStrength: 0.125
  lightness: 0.125
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
